
#include "arte.h"
void logo() {
	cout << " " << endl;
	cout << " " << endl;
	cout << " " << endl;
	cout << " " << endl;
	cout << " " << endl;
	cout << "               88" << endl;
	cout << "               88" << endl;
	cout << "               88" << endl;
	cout << "               88           ,adPPYba,   8b,dPPYba,   ,adPPYba," << endl;
	cout << "               88          a8\"     \"8a  88P'   \"Y8  a8P_____88 " << endl;
	cout << "               88          8b       d8  88          8PP\"\"\"\"\"\"\" " << endl;
	cout << "               88          \"8a,   ,a8\"  88          \"8b,   ,aa " << endl;
	cout << "               88888888888  `\"YbbdP\"'   88           `\"Ybbd8\"'" << endl;
};

void personajes(){
	cout << " " << endl;
	cout << " " << endl;
	cout << " " << endl;
	cout << " " << endl;
	cout << "                                                                               JqMG1:             " << endl;
	cout << "          :8@B@B@P                                                          :@@B@@@B@BG      .    " << endl;
	cout << "         2B@B@B@B@@i       @:                                              ,B@@@B@B@B@BZ    L@B   " << endl;
	cout << "         @@B@B@B@B@B     ,@B                                               k@B@B@B@B@B@B   :@B@@  " << endl;
	cout << "         @B@B@B@B@@5    L@@i                                                B@B@B@B@B@BJ  .@B@B@B " << endl;
	cout << "          qB@B@B@Bv    8@7@                 :7r.                            .B@B@B@B@Bq   @B@B@B@." << endl;
	cout << "             0B:      B@ @i              .@B@@@B@v   .@,                   NBFrrq8Zji5q@:    @M   " << endl;
	cout << "             7B      BM 7B               @B@@@B@@@i . :@:                 @B           ;@    B@   " << endl;
	cout << "             1B;    BM  B:               B@B@@@B@B  .   @.               .B  :,      ,  @O   @B   " << endl;
	cout << "             v@N@. j@  8@                 L@B@B@L        @               M@  @v      Br JB   B@   " << endl;
	cout << "             2B .@L@: r@                      :B  jkPUuSuB@ .jZ,         @r 0@       PB  @   @B   " << endl;
	cout << "             u@  k@B@00                        @.O@ZSEqJ77@:,1O:        .B  @, .      @. BZ 7B@   " << endl;
	cout << "             JBvXkq@B@X                       :@Mj       uO             X@ PB  @,  @  Z@  FuU@B   " << endl;
	cout << "             v@:  @@ :@,                      0@    .   F@              @BvB. FB   BX  B@NP2XB@   " << endl;
	cout << "             UB  JB,                          Sk       @@                 B@  B2   kB  @M   .@@   " << endl;
	cout << "             P@,                              kE      NG                  @. .@     @   @    B@   " << endl;
	cout << "            ,@,@v                             7BqqEX@F                   MB  BB  5  BY  BO   @B   " << endl;
	cout << "            @r  @S                             @    r@                  ;BG. B: .B  EB  1B.  B@   " << endl;
	cout << "           @B    @O                            B.    B                  .775@@  E@   @B@Zu. .@B   " << endl;
	cout << "          5B      @B                     ,rvv7L@.    @r                     @BkL@@2LrBv     .@@   " << endl;
	cout << "          N:       8:                    .r::. .     i:                         U  :rv       Pv   " << endl;
	cout << "    " << endl;
	cout << "   " << endl;
	cout << "          1.- Guerrero                   2.- Arquero                         3.- Mago          " << endl;
	cout << " " << endl;
	cout << " " << endl;

};

void catacumbas1() {
	srand(time(0));
	int a = rand() % 5 + 1;
	if (a == 1) {
		cout << "" << endl;
		cout << "" << endl;
		cout << "       La puerta de las Catacumbas" << endl;
		cout << "" << endl;
		cout << "" << endl;
		cout << "	           ,BqOO               .jEGqNq0q0PNq00@                              :: " << endl;
		cout << "           GPkGM       irLj1uPNE00G8OBBBM@BBB@@r             :M@M;::.::r,   :@G " << endl;
		cout << "          @O0Gu:      0B@@@B@B@BMXFY:.,:iir;rrL:         ,.: i@B@@@B@B@Bq   vB@ " << endl;
		cout << "   @Eur  @MMB@SPO@B@B u@B02u7i.... .                L@0:1@@@PXB@B@B@OMB@Mu.  7: " << endl;
		cout << "   B@B@ vB@B@BMB@B@B@:        iJ0MBB@@@Mq7:       :B@BBM0B@M@ZkPqi    2BO@@     " << endl;
		cout << "  .@E8B   ,j7:;v:irr:.    .28MOBB@B@B@B@B@B@0i      r@M8MGrqBB0O       F8EMO    " << endl;
		cout << "  .BMB@       :@        ,0@B@BOuv:   .rUOB@B@B@k:    .MB@     MO5BM ..,7ZO0M@   " << endl;
		cout << "   @BEu       v@       vBBq@@@B:          iNB@GBBG.    i:    LB80BXiB@B@7FBZB@  " << endl;
		cout << "   .          .L      i@OE@iuB@B.            ,@@ZB@:         .@8NO0 rLLJ. MBB@@ " << endl;
		cout << "             rq:.:   .@O0@L   :@@v           vBUOEO@          @@M@7        OZi  " << endl;
		cout << "        .:XB@B@.     OBNMS      XB@     .7@@@u  BZ0Bi         rr1M              " << endl;
		cout << "     iM@B@B@B@B      @EEB        rB@B@N@@@2     FBq@L    U:  .             uBSL." << endl;
		cout << "      @B@B@Er.      uBEOG         OBM  BY       uBNOP   .B@B@@@BL          M@M@i" << endl;
		cout << "       Fv.          OMq@:        .BM  .@r        @EEB,   .X@B@B@L .j      :@0GB " << endl;
		cout << "                    B00B:        ,@B: vB         0Oq@7         .  BB@Oi   0MEM1 " << endl;
		cout << "     :,.           7BEGO          B@B@B@P:       uB0Mk      :     BOG@    MBO@: " << endl;
		cout << "  LBXB@B@M0SJ      JBPMu        .B@i7i  78@@u    :@PGB     r@B    8@@Pi,..@BMB. " << endl;
		cout << "   GB@B@B@MM@M     v8kO2     :2@@0         k@@    B00@     @BB     LBBB@B.      " << endl;
		cout << "         iO5qB, iu1MMqN8    @B@8             B@   @q0G              ZM@B.   .,Y " << endl;
		cout << "         :GBB@B@B@B@B@B@U  @BP                B@1:OqX@8M@B0SvLk5.          7B@B." << endl;
		cout << "       E@B@B@@@B@M@B@B@B@@@N                   8@B@BE@@B@B@B@@B@@.          iB  " << endl;
		cout << "      MMB@B@B@BY   :2NB@Bv                        ,GB@B1rJju2@BEMO:          U  " << endl;
		cout << "OSBBM88P@Z...                                                :@BMM@B2        7, " << endl;
		cout << "u@B@@@B@M                                                      YN@G8B:          " << endl;
		cout << "1B@B@B@B                                                         S@G8B85iir::,, " << endl;
		cout << "YJ7rr7J:                                                          k@B@B@B@B@B@B2" << endl;
		cout << "                                                                     .7u1u21XE, " << endl;
		cout << "" << endl;
		cout << "" << endl;
	}
	else if (a == 1) {
		cout << "" << endl;
		cout << "" << endl;
		cout << "       Interior de las Catacumbas" << endl;
		cout << "" << endl;
		cout << "" << endl;
		cout << "		                                                          1             L       " << endl;
			cout << "                                                         MB ..         LviF:    " << endl;
			cout << "       :  v    7SO@2r                       JYu:        @B      .     :i:0   .. " << endl;
			cout << "     .B@   :u8 ,          :u1FivvYi        @P...  .Yr. ,v         X8v  ,uuuM@@B " << endl;
			cout << "    1@2  JEBP, .N      Gi      :::, :B    @@     :5ZF:YN@@@@@B@@@B@B@B@B@B@B@7  " << endl;
			cout << "    ,   r8.    .B       rv         :2:    :    :BkrLE@B@B@OSrir777ri,.          " << endl;
			cout << "                 .                  Y       .:@B@B@BM2:                         " << endl;
			cout << "        .        ;         M.        :r5PP8@B@BP:                               " << endl;
			cout << "  rY   ;@        .  .ri    Br     iB@BM82u@@2                                   " << endl;
			cout << "  @q   @1             ,iLri@    F@Pi:r7:F@B                                     " << endl;
			cout << " .@    B      qBv            r@@S rXS  2@r                            7         " << endl;
			cout << " @F   0@     @B            UB@L.v0r  UBq        P@B@BJ               i@         " << endl;
			cout << " :    @:    @B          :B@Bj iNJ.vN@J          @B@..j@.             .@         " << endl;
			cout << "      B    @B         ,B@@urO@B2Pu7            0B@    B@                        " << endl;
			cout << "@2   7@   @B        1B@B@B1J2:.               OB@B    @B2ir                     " << endl;
			cout << "@i   @k  @M      iS@BE1@O,                    O@B.  7@BL:,Bj                    " << endl;
			cout << "     .  @B     :MO@M 7@.                      @B@    . .72S                     " << endl;
			cout << " @.    @B     r@B@B 0@                        @@B               r      ..       " << endl;
			cout << " :    BB    .B@BuBiBP                         @B@             GBO       :::.    " << endl;
			cout << "    7B     B@@,u@B:                          B@Bu.        .0@E           ,Y:   " << endl;
			cout << "     B:    M@B:M@.                            @B@7        :kP               .:  " << endl;
			cout << "    i@     Gq@8@U                             B@M                           r@  " << endl;
			cout << "            LB1.0                             @@v                           jB  " << endl;
			cout << "      .    :B@ 1q                             B@        i0@O.              .PJ  " << endl;
			cout << "     .PEL  B@8 B.                             @B        .:                      " << endl;
			cout << "        .i @uiB@                              B8                                " << endl;
			cout << "           G@rG                               @7                                " << endl;
			cout << "" << endl;
			cout << "" << endl;
	}
	else
	{
		cout << "" << endl;
		cout << "" << endl;
		cout << "       Interior de las Catacumbas" << endl;
		cout << "" << endl;
		cout << "" << endl;
		cout << "		                                                          1             L       " << endl;
		cout << "                                                         MB ..         LviF:    " << endl;
		cout << "       :  v    7SO@2r                       JYu:        @B      .     :i:0   .. " << endl;
		cout << "     .B@   :u8 ,          :u1FivvYi        @P...  .Yr. ,v         X8v  ,uuuM@@B " << endl;
		cout << "    1@2  JEBP, .N      Gi      :::, :B    @@     :5ZF:YN@@@@@B@@@B@B@B@B@B@B@7  " << endl;
		cout << "    ,   r8.    .B       rv         :2:    :    :BkrLE@B@B@OSrir777ri,.          " << endl;
		cout << "                 .                  Y       .:@B@B@BM2:                         " << endl;
		cout << "        .        ;         M.        :r5PP8@B@BP:                               " << endl;
		cout << "  rY   ;@        .  .ri    Br     iB@BM82u@@2                                   " << endl;
		cout << "  @q   @1             ,iLri@    F@Pi:r7:F@B                                     " << endl;
		cout << " .@    B      qBv            r@@S rXS  2@r                            7         " << endl;
		cout << " @F   0@     @B            UB@L.v0r  UBq        P@B@BJ               i@         " << endl;
		cout << " :    @:    @B          :B@Bj iNJ.vN@J          @B@..j@.             .@         " << endl;
		cout << "      B    @B         ,B@@urO@B2Pu7            0B@    B@                        " << endl;
		cout << "@2   7@   @B        1B@B@B1J2:.               OB@B    @B2ir                     " << endl;
		cout << "@i   @k  @M      iS@BE1@O,                    O@B.  7@BL:,Bj                    " << endl;
		cout << "     .  @B     :MO@M 7@.                      @B@    . .72S                     " << endl;
		cout << " @.    @B     r@B@B 0@                        @@B               r      ..       " << endl;
		cout << " :    BB    .B@BuBiBP                         @B@             GBO       :::.    " << endl;
		cout << "    7B     B@@,u@B:                          B@Bu.        .0@E           ,Y:   " << endl;
		cout << "     B:    M@B:M@.                            @B@7        :kP               .:  " << endl;
		cout << "    i@     Gq@8@U                             B@M                           r@  " << endl;
		cout << "            LB1.0                             @@v                           jB  " << endl;
		cout << "      .    :B@ 1q                             B@        i0@O.              .PJ  " << endl;
		cout << "     .PEL  B@8 B.                             @B        .:                      " << endl;
		cout << "        .i @uiB@                              B8                                " << endl;
		cout << "           G@rG                               @7                                " << endl;
		cout << "" << endl;
		cout << "" << endl;
	}
};